---
kind: Service
apiVersion: v1
metadata:
  name: diptiapi
  namespace: demoapp
spec:
  selector:
    app: diptiapp
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer